from financial.models import BankProvider

# Create a simple bank for testing
bank = BankProvider(
    name='Kenya Commercial Bank',
    bank_code='KCB',
    phone_number='+254711087000',
    email='contactcentre@kcb.co.ke',
    website='https://ke.kcbgroup.com',
    loan_application_url='https://ke.kcbgroup.com/loans',
    head_office_address='Kencom House, Moi Avenue, Nairobi',
    swift_code='KCBLKENX',
    license_number='CBK/001/2020',
    nationwide_coverage=True,
    total_branches=250,
    counties_with_branches='Nairobi, Mombasa, Kisumu, Nakuru, Eldoret, Meru, Nyeri',
    offers_motorcycle_loans=True,
    offers_business_loans=True,
    offers_asset_financing=True,
    offers_savings_accounts=True,
    offers_current_accounts=True,
    offers_mobile_banking=True,
    motorcycle_loan_min=50000,
    motorcycle_loan_max=2000000,
    business_loan_min=25000,
    business_loan_max=5000000,
    motorcycle_loan_rate_min=14.0,
    motorcycle_loan_rate_max=24.0,
    business_loan_rate_min=16.0,
    business_loan_rate_max=28.0,
    motorcycle_loan_max_term=60,
    business_loan_max_term=36,
    minimum_income_requirement=15000,
    requires_collateral=True,
    requires_guarantor=True,
    minimum_age=18,
    maximum_age=65,
    application_fee=1000,
    processing_time_days=14,
    online_application=True,
    mobile_app_available=True,
    ussd_banking='*522#',
    is_active=True,
    is_cbb_licensed=True,
    rating=4.2,
    description='Leading bank in Kenya offering comprehensive motorcycle and business loans for boda boda operators.'
)
bank.save()
print(f'Created Bank: {bank.name}')
