# Generated by Django 5.2.4 on 2025-07-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('emergency', '0001_initial'),
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Stage leader or official who collected the contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_contributions', to='members.member'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.member'),
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.stage'),
        ),
        migrations.AddField(
            model_name='welfareaccount',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='welfareaccount',
            name='emergency_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.emergencycase'),
        ),
        migrations.AddField(
            model_name='welfareaccount',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
        migrations.AddField(
            model_name='welfareaccount',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
