# Generated by Django 5.2.4 on 2025-07-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprovider',
            name='loan_application_url',
            field=models.URLField(blank=True, help_text="Direct link to bank's loan application page"),
        ),
    ]
