# Generated by Django 5.2.4 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sms', 'SMS Alert'), ('call', 'Phone Call'), ('whatsapp', 'WhatsApp Message'), ('system', 'System Notification')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20, unique=True)),
                ('accident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('fatal', 'Fatal')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Just Reported'), ('help_dispatched', 'Help Dispatched'), ('hospital', 'Taken to Hospital'), ('resolved', 'Resolved'), ('follow_up', 'Follow-up Required')], default='reported', max_length=20)),
                ('other_parties_involved', models.TextField(blank=True, help_text='Other vehicles, people involved')),
                ('police_involved', models.BooleanField(default=False)),
                ('police_station', models.CharField(blank=True, max_length=200)),
                ('ob_number', models.CharField(blank=True, help_text='Police OB Number', max_length=50)),
                ('injuries_sustained', models.TextField(blank=True)),
                ('hospital_taken_to', models.CharField(blank=True, max_length=200)),
                ('medical_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bike_damaged', models.BooleanField(default=False)),
                ('bike_damage_description', models.TextField(blank=True)),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_claimed', models.BooleanField(default=False)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('claim_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accident Report',
                'verbose_name_plural': 'Accident Reports',
                'ordering': ['-accident_date'],
            },
        ),
    ]
