# Generated by Django 5.2.4 on 2025-07-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accidents', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentalert',
            name='recipient_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='first_responders',
            field=models.ManyToManyField(blank=True, related_name='responded_accidents', to='members.member'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_reports', to='members.member'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accidents', to='members.member'),
        ),
        migrations.AddField(
            model_name='accidentalert',
            name='accident_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accidents.accidentreport'),
        ),
    ]
