# Generated by Django 5.2.4 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('case_type', models.CharField(choices=[('death', 'Death'), ('accident', 'Accident'), ('illness', 'Serious Illness'), ('family_emergency', 'Family Emergency'), ('fire', 'Fire Incident'), ('theft', 'Theft/Robbery')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('approved', 'Approved'), ('disbursed', 'Funds Disbursed'), ('closed', 'Case Closed'), ('rejected', 'Rejected')], default='reported', max_length=20)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_relationship', models.CharField(max_length=100)),
                ('beneficiary_phone', models.CharField(max_length=15)),
                ('beneficiary_id', models.CharField(max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Case',
                'verbose_name_plural': 'Emergency Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilySupportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(help_text='Type of support provided', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_relationship', models.CharField(max_length=100)),
                ('dependents_count', models.PositiveIntegerField(default=0)),
                ('dependents_ages', models.JSONField(default=list, help_text='List of dependent ages')),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('provided_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-provided_date'],
            },
        ),
    ]
