# Generated by Django 5.2.4 on 2025-07-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_emergencies', to='members.member'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_cases', to='members.member'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_emergencies', to='members.member'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_emergencies', to='members.member'),
        ),
        migrations.AddField(
            model_name='familysupportrecord',
            name='emergency_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_records', to='emergency.emergencycase'),
        ),
        migrations.AddField(
            model_name='familysupportrecord',
            name='provided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
