# Generated by Django 5.2.4 on 2025-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_stage_name_organization_interorgcommunication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude coordinate', max_digits=10, null=True),
        ),
    ]
