# Generated by Django 5.2.4 on 2025-07-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_auto_20250722_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.organization'),
        ),
    ]
