# Generated by Django 5.2.4 on 2025-07-22 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('emergency', 'Emergency Loan'), ('bike_repair', 'Bike Repair'), ('fuel', 'Fuel Advance'), ('medical', 'Medical Emergency'), ('school_fees', 'School Fees'), ('business', 'Small Business'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Application Submitted'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('repaying', 'Being Repaid'), ('completed', 'Fully Repaid'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Monthly interest rate %', max_digits=5)),
                ('loan_term_months', models.PositiveIntegerField(default=6, help_text='Loan term in months')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanKitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('contribution', 'Kitty Contribution'), ('loan_disbursement', 'Loan Disbursement'), ('repayment', 'Loan Repayment'), ('interest_earned', 'Interest Earned'), ('penalty', 'Penalty Collection'), ('writeoff', 'Bad Debt Write-off')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_credit', models.BooleanField(help_text='True for money coming in, False for money going out')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('deduction', 'Salary/Earnings Deduction'), ('contribution_offset', 'Offset from Contributions')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
