# Kenyan Counties and their codes
KENYAN_COUNTIES = [
    ('baringo', 'Baringo'),
    ('bomet', 'Bomet'),
    ('bungoma', 'Bungoma'),
    ('busia', 'Busia'),
    ('elgeyo_marakwet', 'Elgeyo-Marakwet'),
    ('embu', 'Embu'),
    ('garissa', 'Garissa'),
    ('homa_bay', 'Homa Bay'),
    ('isiolo', 'Isiolo'),
    ('kajiado', 'Kajiado'),
    ('kakamega', 'Kakamega'),
    ('kericho', 'Kericho'),
    ('kiambu', 'Kiambu'),
    ('kilifi', 'Kilifi'),
    ('kirinyaga', 'Kirinyaga'),
    ('kisii', 'Kisii'),
    ('kisumu', 'Kisumu'),
    ('kitui', 'Kitui'),
    ('kwale', 'Kwale'),
    ('laikipia', 'Laikipia'),
    ('lamu', 'Lamu'),
    ('machakos', 'Machakos'),
    ('makueni', 'Makueni'),
    ('mandera', 'Mandera'),
    ('marsabit', 'Marsabit'),
    ('meru', 'Meru'),
    ('migori', 'Migori'),
    ('mombasa', 'Mombasa'),
    ('muranga', "Murang'a"),
    ('nairobi', 'Nairobi'),
    ('nakuru', 'Nakuru'),
    ('nandi', 'Nandi'),
    ('narok', 'Narok'),
    ('nyamira', 'Nyamira'),
    ('nyandarua', 'Nyandarua'),
    ('nyeri', 'Nyeri'),
    ('samburu', 'Samburu'),
    ('siaya', 'Siaya'),
    ('taita_taveta', 'Taita-Taveta'),
    ('tana_river', 'Tana River'),
    ('tharaka_nithi', 'Tharaka-Nithi'),
    ('trans_nzoia', 'Trans Nzoia'),
    ('turkana', 'Turkana'),
    ('uasin_gishu', 'Uasin Gishu'),
    ('vihiga', 'Vihiga'),
    ('wajir', 'Wajir'),
    ('west_pokot', 'West Pokot'),
]

# Major towns/cities in Kenya
MAJOR_TOWNS = [
    ('nairobi', 'Nairobi'),
    ('mombasa', 'Mombasa'),
    ('kisumu', 'Kisumu'),
    ('nakuru', 'Nakuru'),
    ('eldoret', 'Eldoret'),
    ('thika', 'Thika'),
    ('malindi', 'Malindi'),
    ('kitale', 'Kitale'),
    ('garissa', 'Garissa'),
    ('kakamega', 'Kakamega'),
    ('machakos', 'Machakos'),
    ('meru', 'Meru'),
    ('nyeri', 'Nyeri'),
    ('kericho', 'Kericho'),
    ('kisii', 'Kisii'),
    ('kilifi', 'Kilifi'),
    ('embu', 'Embu'),
    ('mumias', 'Mumias'),
    ('webuye', 'Webuye'),
    ('bungoma', 'Bungoma'),
    ('kapsabet', 'Kapsabet'),
    ('bomet', 'Bomet'),
    ('narok', 'Narok'),
    ('kajiado', 'Kajiado'),
    ('voi', 'Voi'),
    ('taveta', 'Taveta'),
    ('marsabit', 'Marsabit'),
    ('mandera', 'Mandera'),
    ('wajir', 'Wajir'),
    ('isiolo', 'Isiolo'),
    ('nanyuki', 'Nanyuki'),
    ('nyahururu', 'Nyahururu'),
    ('kerugoya', 'Kerugoya'),
    ('murang_a', "Murang'a"),
    ('kenol', 'Kenol'),
    ('limuru', 'Limuru'),
    ('kiambu', 'Kiambu'),
    ('kikuyu', 'Kikuyu'),
    ('ruiru', 'Ruiru'),
    ('juja', 'Juja'),
]
