# Generated by Django 5.2.4 on 2025-07-22 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='National ID Number', max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('zone', models.CharField(help_text='Area/Zone within the stage', max_length=100)),
                ('sacco', models.CharField(blank=True, help_text='SACCO affiliation if any', max_length=200)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('next_of_kin_id', models.CharField(help_text='Next of kin National ID', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('member_number', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('dependents_count', models.PositiveIntegerField(default=0)),
                ('dependents_details', models.JSONField(blank=True, default=list, help_text='List of dependents with their details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['member_number'],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Copy'), ('passport_photo', 'Passport Photo'), ('next_of_kin_id', 'Next of Kin ID Copy'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other Document')], max_length=20)),
                ('document_file', models.FileField(upload_to='member_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
