# Generated by Django 5.2.4 on 2025-07-25 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('coverage_area', models.CharField(help_text='Geographic coverage area', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of SACCO services')),
                ('supports_bodaboda', models.BooleanField(default=True, help_text='Whether this SACCO specifically supports boda boda riders')),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.TextField(blank=True)),
                ('offers_motorcycle_loans', models.BooleanField(default=False)),
                ('offers_insurance', models.BooleanField(default=False)),
                ('offers_savings_accounts', models.BooleanField(default=False)),
                ('offers_emergency_fund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SACCO Affiliation',
                'verbose_name_plural': 'SACCO Affiliations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='sacco',
            field=models.ForeignKey(blank=True, help_text='SACCO affiliation if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.saccoaffiliation'),
        ),
    ]
