# Generated by Django 5.2.4 on 2025-07-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_saccoaffiliation_alter_member_sacco'),
    ]

    operations = [
    ]
