# Generated by Django 5.2.4 on 2025-07-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20250725_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sacco',
            field=models.CharField(blank=True, help_text='SACCO affiliation if any', max_length=200),
        ),
    ]
