# Generated by Django 5.2.4 on 2025-07-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_sacco'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
