# Generated by Django 5.2.4 on 2025-07-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_is_online_member_last_activity_and_more'),
        ('stages', '0005_alter_organization_county_alter_organization_town_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('bike_registration', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('next_of_kin', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=15)),
                ('is_admin', models.BooleanField(default=False, help_text='👑 Admin user with elevated privileges')),
                ('is_super_admin', models.BooleanField(default=False, help_text='👑 Super admin with full system access')),
                ('account_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('profile_completion_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending_verification', 'Pending Verification'), ('complete', 'Complete')], default='incomplete', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
    ]
