# Generated by Django 5.2.4 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('engine_number', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('cc', models.PositiveIntegerField(help_text='Engine capacity in CC')),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current estimated value', max_digits=10)),
                ('logbook_available', models.BooleanField(default=True)),
                ('logbook_location', models.CharField(blank=True, help_text='Where logbook is kept', max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active/In Use'), ('repair', 'Under Repair'), ('stolen', 'Stolen'), ('sold', 'Sold'), ('written_off', 'Written Off'), ('inherited', 'Inherited by Family')], default='active', max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('family_contact_informed', models.BooleanField(default=False)),
                ('next_of_kin_has_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='BikeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('logbook', 'Logbook'), ('insurance_certificate', 'Insurance Certificate'), ('purchase_receipt', 'Purchase Receipt'), ('inspection_certificate', 'Inspection Certificate'), ('registration_certificate', 'Registration Certificate'), ('photo', 'Bike Photo'), ('other', 'Other Document')], max_length=30)),
                ('document_file', models.FileField(upload_to='bike_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BikeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('inheritance', 'Inheritance'), ('sale', 'Sale'), ('gift', 'Gift'), ('recovery', 'Recovery from Theft'), ('insurance_claim', 'Insurance Claim')], max_length=20)),
                ('to_family_member', models.CharField(blank=True, help_text='If transferred to non-member family', max_length=200)),
                ('transfer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_date', models.DateField()),
                ('conditions', models.TextField(blank=True)),
                ('transfer_document', models.FileField(blank=True, upload_to='transfer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
    ]
