# Generated by Django 5.2.4 on 2025-07-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='members.member'),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bikes.bike'),
        ),
        migrations.AddField(
            model_name='biketransfer',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='bikes.bike'),
        ),
        migrations.AddField(
            model_name='biketransfer',
            name='from_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_transferred_from', to='members.member'),
        ),
        migrations.AddField(
            model_name='biketransfer',
            name='to_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes_transferred_to', to='members.member'),
        ),
        migrations.AddField(
            model_name='biketransfer',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_transfers', to='members.member'),
        ),
    ]
